language: ruby
script: "bundle exec jekyll build"

notifications:
  email:
    recipients:
      - eric@sunlightfoundation.com
      - tauberer@govtrack.us
    on_success: change
    on_failure: change